kafka:
  bootstrapservers: localhost:9092
  notifyTopic: notify
  enrollmenttopic: enrollment
  recipientappointmenttopic: recipientappointment
  certifiedtopic: certified
enrollmentcreation:
  maxretrycount: 10
  lengthofsuffixedenrollmentcode: 3
  maxenrollmentcreationallowed: 4
  maxwalkinenrollmentcreationallowed: 10
auth:
  maxotpverifyattempts: 3
  ttlforotpinminutes: 5
  publickey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1mIX9SFluySnfIfT6Jz5
    LdORWO+O0j3L7cF+BLaAdX7JuiN10MTISpyOA5z81YXMSgk0PPLUzHv5DTDPMR3r
    sb6ut/PweLn9sLmwsj9OGSAuH7DFOHVV+Mct9TXBeZu1tzboDhtqKz1PMnBFdmgv
    d2+WnKYtdWfgo8kB82WkGolAT7++efm/HnOkvRkoNbefbbpnELjtcM5uN32HdCpz
    Tm87zshvOoEvkBUcBJdmKNjzLwBc0E2SpthOuxQUw7zSSqnvOOW+sOub6dIgDgR5
    57KyVGKL9NUvlbbp9jglcZERtpE6pRhbjDwBlmzx8NufSap24VzWIUNjy+CiF0J6
    OQIDAQAB
    -----END PUBLIC KEY-----
redis:
  redisurl: "redis://0.0.0.0:6379"
registry:
  url: http://localhost:8081
  addoperationid: add
  searchoperationid: search
  readoperationid: read
keycloak:
  url: https://divoc.xiv.in/keycloak/auth
  realm: divoc
